"""
NoteForge Knowledge Base
Knowledge base documents for the NoteForge AI assistant.
"""

KNOWLEDGE_BASE = [
    {
        "id": "doc_001",
        "topic": "NoteForge Overview",
        "text": "NoteForge is an agentic AI assistant designed for students, self-learners, researchers, and technical professionals. It transforms scattered learning materials such as PDFs, lecture notes, research papers, and online content into organized notes, summaries, revision sheets, concept maps, and self-assessed study plans. NoteForge ensures all responses remain grounded in the provided content without hallucinating information.",
    },
    {
        "id": "doc_002",
        "topic": "Structured Note Generation",
        "text": "NoteForge generates structured notes by analyzing source material and extracting key concepts, definitions, formulas, and relationships. The system organizes information hierarchically with main topics, subtopics, and supporting details. Notes include section headers, bullet points, and numbered lists for clarity. Each note maintains the logical flow of the original material while improving readability and comprehension.",
    },
    {
        "id": "doc_003",
        "topic": "Summarization Techniques",
        "text": "NoteForge employs multiple summarization techniques including extractive summarization (identifying key sentences), abstractive summarization (generating new summaries), and progressive summarization (creating layered summaries from brief to detailed). The system preserves essential information while eliminating redundancy. Summaries include key takeaways, important concepts, and relevant examples from the source material.",
    },
    {
        "id": "doc_004",
        "topic": "Revision Sheet Creation",
        "text": "Revision sheets generated by NoteForge focus on high-yield information likely to appear in exams. These sheets include key definitions, important formulas with variable explanations, critical concepts with brief descriptions, and practice questions. Revision sheets follow the Feynman technique - explaining complex topics in simple terms. The system prioritizes information based on concept depth, prerequisite dependencies, and practical applications.",
    },
    {
        "id": "doc_005",
        "topic": "Concept Mapping",
        "text": "NoteForge creates concept maps that visually represent relationships between ideas. These maps include central concepts as main nodes, supporting concepts as secondary nodes, and directional arrows showing relationships (cause-effect, prerequisite, similar, contrasting). Concept maps help learners understand the interconnected nature of knowledge and identify gaps in their understanding. The system can generate both textual descriptions and structured data for visualization.",
    },
    {
        "id": "doc_006",
        "topic": "Study Plan Generation",
        "text": "NoteForge generates personalized study plans based on learning objectives, available time, and content complexity. Study plans include clear milestones with estimated completion times, prioritization of topics based on dependencies and exam weightage, breaks and revision intervals following spaced repetition principles, and self-assessment checkpoints to measure progress. The system adapts plans based on user performance and feedback.",
    },
    {
        "id": "doc_007",
        "topic": "Quiz and Self-Assessment Generation",
        "text": "NoteForge creates quizzes and self-assessment questions from source material including multiple choice questions, true/false statements, fill-in-the-blank exercises, and short answer questions. Each quiz includes an answer key with explanations. Questions are distributed across difficulty levels (remember, understand, apply, analyze). The system tracks performance over multiple quiz attempts to identify areas needing additional study.",
    },
    {
        "id": "doc_008",
        "topic": "Multi-turn Contextual Conversations",
        "text": "NoteForge maintains conversation context across multiple turns using thread-based memory. The system remembers the user's name (if mentioned), previously discussed topics, specific documents or concepts being studied, and user preferences for note formats. This enables coherent follow-up questions like 'Can you explain that in more detail?' or 'What are the prerequisites for this topic?' without re-explaining the context.",
    },
    {
        "id": "doc_009",
        "topic": "Faithfulness and Grounding",
        "text": "NoteForge prioritizes faithfulness - ensuring all answers are grounded exclusively in the provided source material. The system uses a self-reflection evaluation mechanism that scores responses on a scale of 0.0 to 1.0 based on whether the answer uses only information from the retrieved context. If faithfulness falls below 0.7, the system retries generating the answer. NoteForge explicitly states when information is not available in the source material rather than hallucinating.",
    },
    {
        "id": "doc_010",
        "topic": "Local Text Analysis Tools",
        "text": "NoteForge uses local text analysis tools for tasks that do not require external APIs: text statistics (word count, reading time, complexity score), outline generation from unstructured text, key phrase extraction, and quiz generation from content. These tools run locally and do not require internet connectivity. The tool system is designed to never raise exceptions - errors are handled gracefully by returning error strings.",
    },
    {
        "id": "doc_011",
        "topic": "Handling Technical Content",
        "text": "NoteForge handles technical content including mathematical formulas, code snippets, and scientific notation. Formulas are presented in clean formatting with variable explanations. Code snippets include comments explaining functionality. Technical content is broken down into component parts with dependencies highlighted. The system identifies prerequisite concepts that need to be understood before tackling advanced material.",
    },
    {
        "id": "doc_012",
        "topic": "Source Material Handling",
        "text": "NoteForge processes various source material formats including plain text, PDF content (extracted text), lecture notes, web content, and research paper abstracts. The system extracts the most relevant information based on user queries using semantic similarity search. Each source is treated as a distinct document with its own topic and content to ensure focused retrieval. Vague or general documents produce vague answers - specificity improves quality.",
    },
]
